### ISSUE TITLE
Add a comment explaining the save function in the Book class, bookstore.py

### ISSUE THREAD

**Issue by GabrielGramlich** [GabrielGramlich/readinglist#7]
Use the """ docstring """ format. See the Bookstore class for examples.

**Comment by PickleEric** [comment]
this is completed, I pushed to github

**Comment by GabrielGramlich** [comment]
Do you wanna go ahead and make a pull request for it?

**Comment by PickleEric** [comment]
I do

**Comment by PickleEric** [comment]
Ok i made a pull request
